version: "3"
services:
  redis:
    image: "redis:alpine"
    networks:
      webapp_network:
        ipv4_address: "10.20.30.2"
  web-app:
    restart: on-failure
    build: ./nodejs
    environment:
      PORT: 8080
    ports:
      - "8080:8080"
    networks:
      webapp_network:
        ipv4_address: "10.20.30.3"
  web-app2:
    restart: on-failure
    build: ./nodejs
    environment:
      PORT: 8080
    ports:
      - "8081:8080"
    networks:
      webapp_network:
        ipv4_address: "10.20.30.4"
networks:
  webapp_network:
    ipam:
      driver: default
      config:
        - subnet: "10.20.30.0/24"
